AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 588583220729

Organization:
  MasterAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: Moneyou Organizational Master Account
      AccountId: '588583220729'
      Alias: moneyou-nl

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:

  ProductionOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: production
      ServiceControlPolicies: !Ref DenyUnsupportedRegionsSCP
      Accounts:
        - !Ref MoneyouPushNotificationsProductionAccount
        - !Ref MoneyouAddressbookProductionAccount
        - !Ref MoneyouLimitsProductionAccount
        - !Ref MoneyouXS2AProductionAccount
        - !Ref MoneyouDataProductionAccount
        - !Ref MoneyouAuthproductionAccount
        - !Ref MoneyouTransferBankProductionAccount
        - !Ref Xs2a-devportalAccount
        - !Ref MoneyouOnboardingProductionAccount
        - !Ref MoneyouSnowplowProductionAccount
        - !Ref MoneyouCardNotificationsProductionAccounAccount
        - !Ref MoneyouWalletsProductionAccount
        - !Ref MoneyouScheduledPaymentsProductionAccount

  DevelopmentOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: development
      ServiceControlPolicies: !Ref DenyUnsupportedRegionsSCP
      Accounts:
        - !Ref MoneyouTeam3DevelopmentAccount
        - !Ref MoneyouTaiichiDevAccount
        - !Ref MoneyouDataDevelopmentAccount
        - !Ref MoneyouSandboxDevAccount
        - !Ref Moneyou403DevAccount
        - !Ref MoneyouTeam2DevelopmentAccount
        - !Ref MoneyouTeam1DevelopmentAccount
        - !Ref MoneyouFreshDevelopmentAccount

  SharedOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: shared
      ServiceControlPolicies: !Ref DenyUnsupportedRegionsSCP
      Accounts:
        - !Ref MoneyouPlatformAccount
        - !Ref MoneyouSecurityAccount
        - !Ref MoneyouComplianceAccount
        - !Ref MoneyouLoggingAccount
        - !Ref MoneyouUserAccount

  MoneyouPlatformAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Platform Account
      AccountId: '614335828775'
      RootEmail: olaf.conijn@moneyou.nl
      Alias: moneyou-platform

  MoneyouSecurityAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Security Account
      AccountId: '689483148385'
      RootEmail: security-aws@moneyou.nl
      Alias: moneyou-security

  MoneyouComplianceAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Compliance Account
      AccountId: '939464272238'
      RootEmail: moneyou-compliance-aws@moneyou.nl
      Alias: moneyou-compliance

  MoneyouLoggingAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Logging Account
      AccountId: '276478869702'
      RootEmail: logging-aws@moneyou.nl
      Alias: moneyou-logging

  MoneyouUserAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou User Account
      AccountId: '054949635754'
      RootEmail: user-account-aws@moneyou.nl
      Alias: moneyou-user

  MoneyouTeam3DevelopmentAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Team 3 Development Account
      AccountId: '836623306256'
      RootEmail: team3-dev-aws@moneyou.nl
      Alias: moneyou-team3

  MoneyouTaiichiDevAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Taiichi Dev Account
      AccountId: '756303989147'
      RootEmail: taiichi-dev-aws@moneyou.nl
      Alias: moneyou-taiichi-dev

  MoneyouDataDevelopmentAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Data Development Account
      AccountId: '855594205460'
      RootEmail: data-dev-aws@moneyou.nl
      Alias: moneyou-data-dev

  MoneyouSandboxDevAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Sandbox Dev Account
      AccountId: '098773402887'
      RootEmail: sandbox-dev.aws@moneyou.nl
      Alias: moneyou-sanbox-dev

  Moneyou403DevAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou 403 Dev Account
      AccountId: '419664325495'
      RootEmail: '403-dev-aws@moneyou.nl'

  MoneyouTeam2DevelopmentAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Team 2 Development Account
      AccountId: '912971329312'
      RootEmail: team2-dev-aws@moneyou.nl

  MoneyouTeam1DevelopmentAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Team 1 Development Account
      AccountId: '579001564730'
      RootEmail: team1-dev-aws@moneyou.nl

  MoneyouFreshDevelopmentAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Fresh Development Account
      AccountId: '227947473878'
      RootEmail: fresh-dev-aws@moneyou.nl
      Alias: moneyou-fresh-dev

  MoneyouPushNotificationsProductionAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Push Notifications Production Account
      AccountId: '417229510702'
      RootEmail: push-notifications-prod-aws@moneyou.nl

  MoneyouAddressbookProductionAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Addressbook Production Account
      AccountId: '339539146431'
      RootEmail: fresh-prod-aws@moneyou.nl
      Alias: moneyou-fresh-prod

  MoneyouLimitsProductionAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Limits Production Account
      AccountId: '395788528074'
      RootEmail: limits-prod-aws@moneyou.nl
      Alias: moneyou-limits-prod

  MoneyouXS2AProductionAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou XS2A Production Account
      AccountId: '889444667844'
      RootEmail: xs2a-prod-aws@moneyou.nl
      Alias: moneyou-xs2a-prod

  MoneyouDataProductionAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Data Production Account
      AccountId: '274775030939'
      RootEmail: data-prod-aws@moneyou.nl
      Alias: moneyou-data-prod

  MoneyouAuthproductionAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Auth production Account
      AccountId: '030661853937'
      RootEmail: auth-prod-aws@moneyou.nl

  MoneyouTransferBankProductionAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Transfer Bank Production Account
      AccountId: '419069893087'
      RootEmail: transfer-bank-prod-aws@moneyou.nl

  Xs2a-devportalAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: xs2a-devportal
      AccountId: '451497838888'
      RootEmail: xs2a-devportal-prod-aws@moneyou.nl

  MoneyouOnboardingProductionAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Onboarding Production Account
      AccountId: '672947131878'
      RootEmail: onboarding-prod-aws@moneyou.nl
      Alias: moneyou-onboarding-prod

  MoneyouSnowplowProductionAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Snowplow Production Account
      AccountId: '255743039977'
      RootEmail: snowplow-prod-aws@moneyou.nl
      Alias: moneyou-snowplow-prod

  MoneyouCardNotificationsProductionAccounAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Card Notifications Production Accoun
      AccountId: '505631841448'
      RootEmail: card-notifications-prod-aws@moneyou.nl

  MoneyouWalletsProductionAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Wallets Production Account
      AccountId: '031417794674'
      RootEmail: wallets-prod-aws@moneyou.nl

  MoneyouScheduledPaymentsProductionAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Moneyou Scheduled Payments Production Account
      AccountId: '233052763599'
      RootEmail: sched-payments-prod-aws@moneyou.nl

  DenyUnsupportedRegionsSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: DenyUnsupportedRegions
      Description: denies any action outside of the eu-central-1, eu-west-1 or us-east-1
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyUnsupportedRegions
            Effect: Deny
            NotAction:
              - 'cloudfront:*'
              - 'iam:*'
              - 'route53:*'
              - 'support:*'
            Resource: '*'
            Condition:
              StringNotEquals:
                'aws:RequestedRegion':
                  - eu-central-1
                  - eu-west-1
                  - us-east-1
        

