AWSTemplateFormatVersion: 2010-09-09-OC
Description: Example Organization Formation Template
StackName: organization-formation

Organization:
  MasterAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: My Organization Root
      AccountId: '102625093955'

  DevelopmentOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: development
      ServiceControlPolicies: !Ref RestrictUnusedRegionsSCP
  #     Accounts:
  #     - !Ref DevelopmentAccount1
  #     - !Ref DevelopmentAccount3
  #     - !Ref DevelopmentAccount2

  SharedOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: shared
      ServiceControlPolicies: !Ref RestrictUnusedRegionsSCP
      Accounts:
       - !Ref ServicesAccount
       - !Ref UsersAccount
  #     - !Ref SystemAccount1
  #     - !Ref LoggingAccount

  ProductionOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: production
      ServiceControlPolicies: !Ref RestrictUnusedRegionsSCP
      Accounts:
       - !Ref SystemAccount1
  #     - !Ref SystemAccount2
  #     - !Ref SystemAccount3

  # DevelopmentAccount1:
  #   Type: OC::ORG::Account
  #   Properties:
  #     RootEmail: dev-team1@my-email.com
  #     AccountName: Development Team 1 Account

  # DevelopmentAccount2:
  #   Type: OC::ORG::Account
  #   Properties:
  #     RootEmail: dev-team2@my-email.com
  #     AccountName: Development Team 2 Account

  # DevelopmentAccount3:
  #   Type: OC::ORG::Account
  #   Properties:
  #     RootEmail: dev-team3@my-email.com
  #     AccountName: Development Team 3 Account

  # LoggingAccount:
  #   Type: OC::ORG::Account
  #   Properties:
  #     RootEmail: shared-logging@my-email.com
  #     AccountName: Shared Logging Account

  ComplianceAccount:
    Type: OC::ORG::Account
    Properties:
      RootEmail: shared-compliance@olafconijn.awsapps.com
      AccountName: Shared Compliance Account

  ServicesAccount:
    Type: OC::ORG::Account
    Properties:
      RootEmail: shared-services@olafconijn.awsapps.com
      AccountName: Shared Services Account

  UsersAccount:
    Type: OC::ORG::Account
    Properties:
      RootEmail: users@olafconijn.awsapps.com
      AccountName: Shared Users Account
  #     Metadata:
  #       - AccountOwnerEmail: bill@@my-email.com
  #       - AccountAlias: shared-account

  SystemAccount1:
    Type: OC::ORG::Account
    Properties:
      RootEmail: system1@olafconijn.awsapps.com
      AccountName: System 1 Production Account

  # SystemAccount2:
  #   Type: OC::ORG::Account
  #   Properties:
  #     RootEmail: system-2-account@my-email.com
  #     AccountName: System 2 Production Account
  #     Metadata:
  #       - AccountOwnerEmail: bill@@my-email.com
  #       - AccountAlias: system-2-account

  # SystemAccount3:
  #   Type: OC::ORG::Account
  #   Properties:
  #     RootEmail: system-3-account@my-email.com
  #     AccountName: System 3 Production Account
  #     Metadata:
  #       - AccountOwnerEmail: bill@@my-email.com
  #       - AccountAlias: system-3-account

  RestrictUnusedRegionsSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: RestrictUnusedRegions
      Description: Restrict Unused regions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: DenyUnsupportedRegions
          Effect: Deny
          NotAction:
          - cloudfront:*
          - iam:*
          - route53:*
          - support:*
          Resource: "*"
          Condition:
            StringNotEquals:
              aws:RequestedRegion:
              - eu-west-1
              - us-east-1
              - eu-central-1

Metadata:

Parameters:

Mappings:

Conditions:

Resources:

  CloudTrailBucket:
    Type: OC::ORG::SharedBucket
    OrganizationBindings:
      Regions: eu-central-1
      Accounts: !Ref ComplianceAccount
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketName: !Sub
        - 'CloudTrail-${RootId}'
        - RootId: !Ref Root

  CloudTrail:
    Type: OC::ORG::CloudTrail
    OrganizationBindings:
      Regions: eu-central-1
      Accounts: '*'
      IncludeMasterAccount: true
    Properties:
      TemplateURL: ./example.iam.baseline.yml
      Parameters:
        UsersAccount: !Ref UsersAccount

  IamBaseLine:
    Type: AWS::CloudFormation::Stack
    OrganizationBindings:
      Regions: eu-central-1
      Accounts: '*'
      IncludeMasterAccount: false
    Properties:
      TemplateURL: ./example.iam.baseline.yml
      Parameters:
        UsersAccount: !Ref UsersAccount

  DeveloperRole:
    Type: OC::ORG::SharedRole
    OrganizationBindings:
      Regions: eu-central-1
      OrganizationalUnits: !Ref DevelopmentOU
    Properties:
      UsersAccount: !Ref UsersAccount
      RoleName: DeveloperRole
      ManagedPolicyArns: arn:aws:iam::aws:policy/PowerUserAccess
      MaxSessionDuration: 3600

  DevOpsRole:
    Type: OC::ORG::SharedRole
    OrganizationBindings:
      Regions: eu-central-1
      IncludeMasterAccount: true
      OrganizationalUnits:
        - !Ref SharedOU
        - !Ref ProductionOU
    Properties:
      UsersAccount: !Ref UsersAccount
      RoleName: DevOpsRole
      ManagedPolicyArns: arn:aws:iam::aws:policy/PowerUserAccess
      MaxSessionDuration: 3600
Outputs: