AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 507468909204

Organization:
  MasterAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      Alias: org-formation-master
      AccountName: Organization Formation Test Account
      AccountId: '507468909204'

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      ServiceControlPolicies: '*'


  ProductionOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: production
      ServiceControlPolicies: '*'

  DevelopmentOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: development
      ServiceControlPolicies: '*'

  SharedOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: shared
      Accounts: '*'

  SharedComplianceAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Shared Compliance Account
      AccountId: '295223382687'
      RootEmail: shared-compliance-2@olafconijn.awsapps.com
      Alias: org-formation-compliance
      Tags:
        budget-alarm-threshold: '250'
        account-owner-email: olaf@email.com

  SharedUsersAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Shared Users Account
      AccountId: '998174572440'
      RootEmail: users-2@olafconijn.awsapps.com
      # Alias: org-formation-users
      # Tags:
      #   budget-alarm-threshold: '100'
      #   account-owner-email: olaf@email.com

  SharedServicesAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Shared Services Account
      AccountId: '516455415878'
      RootEmail: shared-services-2@olafconijn.awsapps.com
      Alias: org-formation-services
      Tags:
        budget-alarm-threshold: '2500'
        account-owner-email: olaf@email.com

  RestrictUnusedRegionsSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: RestrictUnusedRegions
      Description: Restrict Unused regions
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DenyUnsupportedRegions
            Effect: Deny
            NotAction:
              - 'cloudfront:*'
              - 'iam:*'
              - 'route53:*'
              - 'support:*'
            Resource: '*'
            Condition:
              StringNotEquals:
                'aws:RequestedRegion':
                  - eu-west-1
                  - us-east-1
                  - eu-central-1


  RestrictUnusedRegionsSCP2:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: RestrictUnusedRegions2
      Description: Restrict Unused regions
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DenyUnsupportedRegions
            Effect: Deny
            NotAction:
              - 'cloudfront:*'
              - 'iam:*'
              - 'route53:*'
              - 'support:*'
            Resource: '*'
            Condition:
              StringNotEquals:
                'aws:RequestedRegion':
                  - eu-west-1
                  - us-east-1
                  - eu-central-1


