AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 507468909204

Organization: !Include ./organization.yml

Resources:

  Budget:
    OrganizationBinding:
      Region: eu-central-1
      AccountsWithTag: budget-alarm-threshold
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: !Sub 'my-budget-${AWSAccount.Alias}'
        BudgetLimit:
          Amount: !GetAtt AWSAccount.Tags.budget-alarm-threshold
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 1
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !GetAtt AWSAccount.Tags.account-owner-email

