AWSTemplateFormatVersion: '2010-09-09-OC'

Organization: !Include ./organization.yml

OrganizationBinding:
  AccountsWithTag: budget-alarm-threshold
OrganizationBindingRegion: eu-central-1\

Parameters:

  resourcePrefix:
    Type: String
    Default: my

Resources:

  Budget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: !Sub '${resourcePrefix}-budget-${AWSAccount.Alias}'
        BudgetLimit:
          Amount: !GetAtt AWSAccount.Tags.budget-alarm-threshold
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 1
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !GetAtt AWSAccount.Tags.account-owner-email

