AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 507468909204

Organization: !Include ./organization.yml

Resources:

  CloudFormationStackSetAdministrationRole:
    Type: AWS::IAM::Role
    OrganizationBinding:
      Region: eu-central-1
      IncludeMasterAccount: true
    Properties:
      RoleName: AWSCloudFormationStackSetAdministrationRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AssumeRole-AWSCloudFormationStackSetExecutionRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - 'arn:aws:iam::*:role/AWSCloudFormationStackSetExecutionRole'

  CloudFormationStackSetExecutionRole:
    Type: AWS::IAM::Role
    OrganizationBinding:
      Account: '*'
      Region: eu-central-1
    Properties:
      RoleName: AWSCloudFormationStackSetExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref MasterAccount
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AWSCloudFormationStackSetExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - cloudformation:*
              - s3:*
              - sns:*
              Resource: '*'
