

AWSTemplateFormatVersion: '2010-09-09-OC'

Organization: !Include ./organization.yml
DefaultOrganizationBindingRegion: eu-central-1

Parameters:

  resourcePrefix:
    Type: String
    Default: my

  functionName:
    Type: String

  functionAccount:
    Type: String
    Default: !Ref SharedServicesAccount


OrganizationBindings:

  FunctionAccountBinding:
    Account: !Ref functionAccount

  InvokePermissionAccountBinding:
    Account: '*'
    ExcludeAccount: !Ref functionAccount


Resources:

  InvokeFunctionPolicy:
    Type: AWS::IAM::ManagedPolicy
    OrganizationBinding: !Ref InvokePermissionAccountBinding
    Properties:
      ManagedPolicyName: !Sub '${resourcePrefix}-${functionName}-invoke-policy'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource: !Sub 'arn:aws:lambda:*:${functionAccount}:function:${functionName}'

  InvokePermissions:
    Type: AWS::Lambda::Permission
    OrganizationBinding: !Ref FunctionAccountBinding
    Foreach: !Ref InvokePermissionAccountBinding
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref functionName
      Principal: !Ref CurrentAccount