AWSTemplateFormatVersion: 2010-09-09-OC

# include organization template.
Organization: !Include ./organization.yml

# default region used when exe.
OrganizationBindingRegion: eu-central-1

Parameters:

  resourcePrefix:
    Type: String
    Default: my

  usersAccount:
    Type: String
    Default: !Ref SharedUsersAccount

OrganizationBindings:

  UsersAccountBinding:
    Account: !Ref usersAccount

  RoleAccountBinding:
    Account: '*'
    ExcludeAccount: !Ref usersAccount

Resources:

  # this resource will only be created in the SharedUsersAccount
  DeveloperGroup:
    OrganizationBinding: !Ref UsersAccountBinding
    Type: AWS::IAM::Group
    Properties:
      GroupName: DevelopersGroup
      Policies:
        - PolicyName: assume-roles
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: Fn::EnumTargetAccounts RoleAccountBinding 'arn:aws:iam::${account}:role/DeveloperRole'

  # this resource will only be created in all accounts (except the organizational master)
  DeveloperRole:
    OrganizationBinding: !Ref RoleAccountBinding
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/PowerUserAccess
      RoleName: DeveloperRole
      AssumeRolePolicyDocument:
       Version: 2012-10-17
       Statement:
         - Effect: Allow
           Action: sts:AssumeRole
           Principal:
            AWS: Fn::EnumTargetAccounts UsersAccountBinding '${account}' # role can only be assumed from SharedUsersAccount
