AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 507468909204

Organization:
  MasterAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: Organization Formation Test Account
      AccountId: '507468909204'
      Alias: org-formation-master

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      ServiceControlPolicies:
        - !Ref DenyChangeOfOrgRoleSCP
        - !Ref RestrictUnusedRegionsSCP

  ProductionOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: production
      ServiceControlPolicies: !Ref RestrictUnusedRegionsSCP

  DevelopmentOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: development
      ServiceControlPolicies: !Ref RestrictUnusedRegionsSCP

  SharedOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: shared
      Accounts:
        - !Ref SharedComplianceAccount
        - !Ref SharedServicesAccount

  SharedUsersAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Shared Users Account
      AccountId: '998174572440'
      RootEmail: users-2@olafconijn.awsapps.com
      Alias: org-formation-users
      Tags:
        budget-alarm-threshold: '100'
        account-owner-email: olaf@email.com

  SharedComplianceAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Shared Compliance Account
      AccountId: '295223382687'
      RootEmail: shared-compliance-2@olafconijn.awsapps.com
      Alias: org-formation-compliance
      Tags:
        budget-alarm-threshold: '200'
        account-owner-email: olaf@email.com

  SharedServicesAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Shared Services Account
      AccountId: '516455415878'
      RootEmail: shared-services-2@olafconijn.awsapps.com
      Alias: org-formation-services
      Tags:
        budget-alarm-threshold: '22'
        account-owner-email: olaf@email.com

  DenyChangeOfOrgRoleSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: DenyChangeOfOrgRole
      Description: Deny changing the IAM role used for organization access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyChangeOfOrgRole
            Effect: Deny
            Action:
              - 'iam:Attach*'
              - 'iam:Create*'
              - 'iam:Delete*'
              - 'iam:Detach*'
              - 'iam:PutRole*'
              - 'iam:Update*'
            Resource:
              - 'arn:aws:iam::*:role/OrganizationAccountAccessRole'
        
  RestrictUnusedRegionsSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: RestrictUnusedRegions
      Description: Restrict Unused regions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyUnsupportedRegions
            Effect: Deny
            NotAction:
              - 'cloudfront:*'
              - 'iam:*'
              - 'route53:*'
              - 'support:*'
            Resource: '*'
            Condition:
              StringNotEquals:
                'aws:RequestedRegion':
                  - eu-west-1
                  - us-east-1
                  - eu-central-1
        

